### PR TITLE
Add `relatorDataCache` in serialize method to avoid duplicate lookups during `recurseRelators` call

### LINKED ISSUE #24: [FR] Remove additional fetch calls during recurseRelators calls.
## Is your feature request related to a problem? <sup>*</sup>

The `Relator` fetch method is excessively called during `recurseRelators` due to the algorithm neglecting to remove finished work from queue.

As an example:

**Code:**
```ts
  it("Should bypass recurse cycles after data fetched", async () => {
    type A = { id: string; prop: string }
    type B = { id: string; prop: string }
    let fetchCounter = 0

    const SerializerB = new Serializer<B>("b")
    const AtoBRelator = new Relator<A, B>(async (data) => {
      fetchCounter++
      return { id: "1", prop: "b" }
    }, SerializerB)

    const SerializerA = new Serializer<A>("a", {
      relators: { b: AtoBRelator },
    })

    const serialized = await SerializerA.serialize(
      { id: "1", prop: "a" },
      { depth: 10 }
    )

    console.log(fetchCounter)
  })
```

**Output:**
```
  console.log
    11
```

## Describe the solution you'd like<sup>*</sup>

If the work is removed from the queue after resolving, the algo can exit earlier :) I will submit a followup PR.

## Additional context

I believe there may be further optimizations possible to reduce duplicate fetch calls during serialization, but this is an easy first pass.

### PR DESCRIPTION
**Pull request by jaridmargolin**
# Description

Fixes #24 

# Notes

All of the tests are passing, but this was more or less a full rewrite of the `recurseRelators` internals. A thorough set of eyes would be greatly appreciated 🙏

### CODE REVIEW

**Comment by jrandolf** [comment]
Looks good, but can you add some tests related to the cache?

**Comment by jaridmargolin** [comment]
The `issue-24.test`, which updated it's assertion value from 2 -> 4, should give e2e coverage that the cache is working as expected.

I don't mind writing some unit tests around the individual serialize methods impacted, but it doesn't seem that follows the conventions of the project. For example, the tests in `serialzier.tests` appear to be e2e, testing that serialize works. There don't appear to be tests for the individual class methods.

If I were to try and add more granular tests around the cache, rather than relying on the `issue-24.test`, I could:
1. Write a test to show that the cache is correctly populated when calling `relator.getRelationship`
2. Write a test to show that the cache is correctly populated when calling `serializer.createResource` (this IMO would be the best test, and more or less would make test 1 unnecessary)

There isn't really a way to test the cache within the `serialize` method without testing e2e as we did in the `issue-24.test`. Might be able to use jest spies to check the cache state as it is passed into `recurseRelators`?

---

Reading the summary above, do you have opinions on what you are looking to see? ... and once again, thank you taking the time to help me get this to the finish line 🙏

**Comment by jrandolf** [comment]
Both options are desirable. We didn't write tests for particular methods because the code is abstract enough to read and understand, but considering this threads through several functions, a unit test will help understand the precise locality of the cache option.

You don't need to test the cache in the serialize method.

**Comment by jaridmargolin** [comment]
@jun-sheaf - I just pushed updates adding some additional test coverage.

**Comment by jrandolf** [comment]
Looks good, I'll publish it in a few days.

**Pull request merged**
